apiVersion: skaffold/v2beta28
kind: Config
build:
  local:
    push: false
  artifacts:
    - image: yelhadad/shopping
      context: ./
      docker:
        dockerfile: Dockerfile
      sync:
        infer:
          - '**/*.py'
deploy:
  kubectl:
    manifests:
      - ./k8s/*