apiVersion: skaffold/v2beta28
kind: Config
build:
  local:
    push: false
  artifacts:
    - image: yelhadad/shopping
      context: ./server
      docker:
        dockerfile: Dockerfile
      sync:
        infer:
          - "**/*.py"
    - image: yelhadad/shopping-client
      context: ./client
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: "*/**/*.ts*"
            dest: "."
deploy:
  kubectl:
    manifests:
      - ./k8s/*
