---
apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-cfg
  labels:
    app: postgres
data:
  POSTGRES_DB: shopping
  POSTGRES_USER: admin
  POSTGRES_PASSWORD: mamram
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
        - name: postgres
          image: postgres
          imagePullPolicy: "IfNotPresent"
          args:
          ports:
            - containerPort: 5432
          envFrom:
            - configMapRef:
                name: postgres-cfg
---
apiVersion: v1
kind: Service
metadata:
  name: postgres-srv
spec:
  selector:
    app: postgres
  ports:
    - protocol: TCP
      port: 5432
      targetPort: 5432
